[project]
name = "python"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "starlette>=0.37.2",
    "httptools>=0.6.4",
    "uvicorn[standard]>=0.35.0",
    "uvloop>=0.21.0",
]
